// Challenges.jsx
const challenges = [
  "Yo nunca he sido detenido/a por la policía.",
  "Yo nunca he hecho paracaidismo.",
  "Yo nunca he mentido sobre mi edad.",
  "Yo nunca he cantado en un karaoke.",
  "Yo nunca he viajado solo/a a otro país.",
  "Yo nunca me he escapado de clase.",
  "Yo nunca he roto un hueso.",
  "Yo nunca he sido arrestado/a.",
  "Yo nunca he sido expulsado/a de un bar o club.",
  "Yo nunca he mentido a un amigo/a.",
  "Yo nunca he conducido sin licencia.",
  "Yo nunca he enviado un mensaje de texto a la persona equivocada.",
  "Yo nunca he sido infiel.",
  "Yo nunca he chocado un coche.",
  "Yo nunca he olvidado el cumpleaños de un ser querido.",
  "Yo nunca he salido en televisión.",
  "Yo nunca he ido a una boda sin ser invitado/a.",
  "Yo nunca he hecho trampa en un examen.",
  "Yo nunca he fingido estar enfermo/a para no ir al trabajo o a la escuela.",
  "Yo nunca he perdido mi teléfono.",
  "Yo nunca he subido a una montaña rusa.",
  "Yo nunca he dicho 'te amo' sin sentirlo.",
  "Yo nunca he ganado la lotería o un concurso.",
  "Yo nunca he estado en una pelea física.",
  "Yo nunca he hablado mal de alguien a sus espaldas.",
  "Yo nunca he sido rechazado/a en público.",
  "Yo nunca he tenido una cita a ciegas.",
  "Yo nunca he viajado sin un plan.",
  "Yo nunca he usado una identidad falsa en internet.",
  "Yo nunca he hecho una broma telefónica.",
  "Yo nunca he llorado viendo una película.",
  "Yo nunca he subido fotos comprometedoras a redes sociales.",
  "Yo nunca he estado en un accidente de coche.",
  "Yo nunca he dejado una propina muy alta por error.",
  "Yo nunca he hecho un tatuaje.",
  "Yo nunca he mentido sobre estar sobrio/a.",
  "Yo nunca he jugado con fuego.",
  "Yo nunca he dejado una relación sin dar explicaciones.",
  "Yo nunca he bailado sobre una mesa.",
  "Yo nunca he tenido un amor a primera vista.",
  "Yo nunca he viajado en avión en primera clase.",
  "Yo nunca he sido el/la mejor de mi clase.",
  "Yo nunca he tenido un accidente embarazoso en público.",
  "Yo nunca he sido testigo de un crimen.",
  "Yo nunca he olvidado el nombre de alguien mientras hablaba con esa persona.",
  "Yo nunca he fingido saber algo cuando no tenía idea.",
  "Yo nunca he dado un discurso en público.",
  "Yo nunca he comido algo que cayó al suelo.",
  "Yo nunca he dejado de hablar a un amigo/a por una discusión.",
  "Yo nunca he perdido algo valioso y mentido al respecto.",
  "Yo nunca he estado en un país exótico.",
  "Yo nunca he roto el corazón de alguien.",
  "Yo nunca he salido con alguien solo por su apariencia.",
  "Yo nunca he hecho una compra impulsiva que luego lamenté.",
  "Yo nunca he fingido un acento.",
  "Yo nunca he dormido en la calle.",
  "Yo nunca he visto un fantasma o algo paranormal.",
  "Yo nunca he tenido una relación a distancia.",
  "Yo nunca he comido comida de mi mascota.",
  "Yo nunca he hecho un maratón de una serie completa en un solo día.",
  "Yo nunca he tenido una experiencia cercana a la muerte.",
  "Yo nunca he sido expulsado/a de un restaurante.",
  "Yo nunca he estado tan borracho/a que no recuerdo lo que pasó.",
  "Yo nunca he viajado en tren de larga distancia.",
  "Yo nunca he ganado un premio en un sorteo.",
  "Yo nunca he hecho algo de lo que me arrepiento profundamente.",
  "Yo nunca he hablado con alguien famoso.",
  "Yo nunca he tenido una mascota exótica.",
  "Yo nunca he dado un regalo que me dieron a mí.",
  "Yo nunca he dejado un trabajo sin avisar.",
  "Yo nunca he estado en una despedida de soltero/a.",
  "Yo nunca he comido algo que odiaba solo para no hacer sentir mal a alguien.",
  "Yo nunca he sido sorprendido/a haciendo algo vergonzoso.",
  "Yo nunca he ido de camping.",
  "Yo nunca he hecho paravelismo.",
  "Yo nunca he pedido matrimonio o me han pedido matrimonio.",
  "Yo nunca he tenido un trabajo que odiaba.",
  "Yo nunca he mentido para salir de una cita.",
  "Yo nunca he nadado desnudo/a.",
  "Yo nunca he compartido un secreto que me contaron en confianza.",
  "Yo nunca he fingido estar feliz cuando no lo estaba.",
  "Yo nunca he robado algo en una tienda.",
  "Yo nunca he hecho un regalo hecho a mano.",
  "Yo nunca he comido algo caducado.",
  "Yo nunca he tenido un amor platónico.",
  "Yo nunca he hecho un ridículo en público por estar distraído/a.",
  "Yo nunca he intentado ligar con alguien usando una frase de película.",
  "Yo nunca he asistido a un concierto solo/a.",
  "Yo nunca he dejado una propina muy baja.",
  "Yo nunca he sido testigo de una boda improvisada.",
  "Yo nunca he conocido a alguien que se convirtiera en mi mejor amigo/a al instante.",
  "Yo nunca he dejado de hablar a un familiar.",
  "Yo nunca he sido atrapado/a mintiendo.",
  "Yo nunca he salido de casa con la ropa al revés o desarreglada.",
  "Yo nunca he sido echado/a de un lugar.",
  "Yo nunca he viajado en globo aerostático.",
  "Yo nunca he tenido una experiencia de vida salvaje (como un safari).",
  "Yo nunca he mentido sobre un logro personal.",
  "Yo nunca he tomado más de 10 shots en una noche."
];

export default challenges;